name = "Cozy Create Redux"
author = "Kaleb"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fb7d4ed491a46059a60d0319fefa4533c45efc2113af66dfcd915404f821cb1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
