name = "Cozy Create Redux"
author = "Kaleb"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2f9f198345abcd6efd09133b22be6ed7adfd21be5fb158d323509900e90fe83"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
