name = "Cozy Create Redux"
author = "Kaleb"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0cceb8b1ce2fe35770f7b5a11c02251ae791d943e313378d663497727d334555"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
